/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Health check response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            ok: true;
                            /** @enum {string} */
                            service: "finnish-national-parks-api";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to Google OAuth consent screen */
                302: {
                    headers: {
                        /** @description Google OAuth authorization URL */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description OAuth not configured */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    code?: string;
                    error?: string;
                    state?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to frontend after authentication */
                302: {
                    headers: {
                        /** @description Frontend redirect URL */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description OAuth not configured */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current authenticated user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example admin@example.com */
                            email: string;
                            /** @example 123456789 */
                            id: string;
                            /** @example Admin User */
                            name: string;
                            /** @example https://lh3.googleusercontent.com/photo.jpg */
                            picture: string;
                        };
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
                /** @description OAuth not configured */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description OAuth not configured */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    type?: "outdoor-recreation-area" | "state-hiking-area" | "wilderness-area" | "national-park" | "other-nature-reserve" | "nature-trail" | "hiking-trail";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Catalog park list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            parks: {
                                areaKm2: number | null;
                                boundingBox: {
                                    maxLat: number;
                                    maxLon: number;
                                    minLat: number;
                                    minLon: number;
                                };
                                displayTypeName?: string | null;
                                establishmentYear: number | null;
                                location: string;
                                logo: {
                                    key: string;
                                    /** Format: date-time */
                                    updatedAt: string;
                                    /** Format: uri */
                                    url: string;
                                } | null;
                                luontoonUrl: string | null;
                                map: {
                                    key: string;
                                    /** Format: date-time */
                                    updatedAt: string;
                                    /** Format: uri */
                                    url: string;
                                } | null;
                                markerPoint: {
                                    lat: number;
                                    lon: number;
                                };
                                name: string;
                                slug: string;
                                type: {
                                    code: number;
                                    id: number;
                                    name: string;
                                    /** @enum {string} */
                                    slug: "outdoor-recreation-area" | "state-hiking-area" | "wilderness-area" | "national-park" | "other-nature-reserve" | "nature-trail" | "hiking-trail";
                                };
                            }[];
                        };
                    };
                };
                /** @description Catalog park list not modified */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parks/removed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed parks for admin visibility management */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            parks: {
                                areaKm2: number | null;
                                boundingBox: {
                                    maxLat: number;
                                    maxLon: number;
                                    minLat: number;
                                    minLon: number;
                                };
                                displayTypeName?: string | null;
                                establishmentYear: number | null;
                                location: string;
                                logo: {
                                    key: string;
                                    /** Format: date-time */
                                    updatedAt: string;
                                    /** Format: uri */
                                    url: string;
                                } | null;
                                luontoonUrl: string | null;
                                map: {
                                    key: string;
                                    /** Format: date-time */
                                    updatedAt: string;
                                    /** Format: uri */
                                    url: string;
                                } | null;
                                markerPoint: {
                                    lat: number;
                                    lon: number;
                                };
                                name: string;
                                slug: string;
                                type: {
                                    code: number;
                                    id: number;
                                    name: string;
                                    /** @enum {string} */
                                    slug: "outdoor-recreation-area" | "state-hiking-area" | "wilderness-area" | "national-park" | "other-nature-reserve" | "nature-trail" | "hiking-trail";
                                };
                                /** @enum {string} */
                                catalogStatus: "active" | "inactive";
                                /** @enum {boolean} */
                                removed: true;
                                updatedAt: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parks/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    includeBoundary?: "true" | "false";
                };
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Catalog park detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            areaKm2: number | null;
                            boundingBox: {
                                maxLat: number;
                                maxLon: number;
                                minLat: number;
                                minLon: number;
                            };
                            displayTypeName?: string | null;
                            establishmentYear: number | null;
                            location: string;
                            logo: {
                                key: string;
                                /** Format: date-time */
                                updatedAt: string;
                                /** Format: uri */
                                url: string;
                            } | null;
                            luontoonUrl: string | null;
                            map: {
                                key: string;
                                /** Format: date-time */
                                updatedAt: string;
                                /** Format: uri */
                                url: string;
                            } | null;
                            markerPoint: {
                                lat: number;
                                lon: number;
                            };
                            name: string;
                            slug: string;
                            type: {
                                code: number;
                                id: number;
                                name: string;
                                /** @enum {string} */
                                slug: "outdoor-recreation-area" | "state-hiking-area" | "wilderness-area" | "national-park" | "other-nature-reserve" | "nature-trail" | "hiking-trail";
                            };
                            boundaryGeoJson?: {
                                features: {
                                    geometry: {
                                        coordinates: number[][][];
                                        /** @enum {string} */
                                        type: "Polygon";
                                    } | {
                                        coordinates: number[][];
                                        /** @enum {string} */
                                        type: "LineString";
                                    };
                                    /** @enum {string} */
                                    type: "Feature";
                                }[];
                                /** @enum {string} */
                                type: "FeatureCollection";
                            };
                            /** @enum {string} */
                            catalogStatus: "active" | "inactive";
                            lipasId: number;
                            municipalityCode: number | null;
                            postalOffice: string | null;
                            /** Format: date-time */
                            sourceEventDate: string | null;
                            updatedAt: string;
                        };
                    };
                };
                /** @description Catalog park detail not modified */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Park was not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parks/{slug}/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Park visit history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            visitedSummary: {
                                lastVisitedOn: string | null;
                                visitCount: number;
                                visited: boolean;
                            };
                            visits: {
                                author: string | null;
                                createdAt: string;
                                id: number;
                                images: {
                                    id: number;
                                    /** Format: uri */
                                    fullUrl: string;
                                    /** Format: uri */
                                    thumbUrl: string;
                                    fullWidth: number | null;
                                    fullHeight: number | null;
                                    thumbWidth: number | null;
                                    thumbHeight: number | null;
                                    originalName: string | null;
                                    displayOrder: number;
                                    createdAt: string;
                                }[];
                                note: string | null;
                                route: string | null;
                                updatedAt: string;
                                visitedOn: string;
                            }[];
                        };
                    };
                };
                /** @description Park was not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        author?: string | null;
                        note?: string | null;
                        route?: string | null;
                        visitedOn: string;
                    };
                };
            };
            responses: {
                /** @description Created park visit */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            author: string | null;
                            createdAt: string;
                            id: number;
                            images: {
                                id: number;
                                /** Format: uri */
                                fullUrl: string;
                                /** Format: uri */
                                thumbUrl: string;
                                fullWidth: number | null;
                                fullHeight: number | null;
                                thumbWidth: number | null;
                                thumbHeight: number | null;
                                originalName: string | null;
                                displayOrder: number;
                                createdAt: string;
                            }[];
                            note: string | null;
                            route: string | null;
                            updatedAt: string;
                            visitedOn: string;
                        };
                    };
                };
                /** @description Park was not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/home-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Public visit summary for the home page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date-time */
                            updatedAt: string | null;
                            version: number;
                            latestVisitEntries: {
                                /** Format: date-time */
                                createdAt: string;
                                id: number;
                                park: {
                                    name: string;
                                    slug: string;
                                };
                                /** Format: date-time */
                                updatedAt: string;
                                visitedOn: string;
                            }[];
                            mostVisitedParks: {
                                lastVisitedOn: string | null;
                                park: {
                                    name: string;
                                    slug: string;
                                };
                                visitCount: number;
                            }[];
                            progressByType: {
                                totalParks: number;
                                totalVisits: number;
                                type: {
                                    code: number;
                                    id: number;
                                    name: string;
                                    /** @enum {string} */
                                    slug: "outdoor-recreation-area" | "state-hiking-area" | "wilderness-area" | "national-park" | "other-nature-reserve" | "nature-trail" | "hiking-trail";
                                };
                                visitedParks: number;
                            }[];
                            recentVisits: {
                                park: {
                                    name: string;
                                    slug: string;
                                };
                                visitedSummary: {
                                    lastVisitedOn: string | null;
                                    visitCount: number;
                                    visited: boolean;
                                };
                            }[];
                            seasonalVisitCounts: {
                                autumn: number;
                                spring: number;
                                summer: number;
                                winter: number;
                            };
                            totalVisits: number;
                            uniqueVisitedParks: number;
                        };
                    };
                };
                /** @description Public home summary not modified */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/map-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Public park and visit summary for the map page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date-time */
                            updatedAt: string | null;
                            version: number;
                            parks: {
                                areaKm2: number | null;
                                boundingBox: {
                                    maxLat: number;
                                    maxLon: number;
                                    minLat: number;
                                    minLon: number;
                                };
                                displayTypeName?: string | null;
                                establishmentYear: number | null;
                                location: string;
                                logo: {
                                    key: string;
                                    /** Format: date-time */
                                    updatedAt: string;
                                    /** Format: uri */
                                    url: string;
                                } | null;
                                luontoonUrl: string | null;
                                map: {
                                    key: string;
                                    /** Format: date-time */
                                    updatedAt: string;
                                    /** Format: uri */
                                    url: string;
                                } | null;
                                markerPoint: {
                                    lat: number;
                                    lon: number;
                                };
                                name: string;
                                slug: string;
                                type: {
                                    code: number;
                                    id: number;
                                    name: string;
                                    /** @enum {string} */
                                    slug: "outdoor-recreation-area" | "state-hiking-area" | "wilderness-area" | "national-park" | "other-nature-reserve" | "nature-trail" | "hiking-trail";
                                };
                                visitedSummary: {
                                    lastVisitedOn: string | null;
                                    visitCount: number;
                                    visited: boolean;
                                };
                            }[];
                        };
                    };
                };
                /** @description Public map summary not modified */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Visit list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            visits: {
                                author: string | null;
                                createdAt: string;
                                id: number;
                                images: {
                                    id: number;
                                    /** Format: uri */
                                    fullUrl: string;
                                    /** Format: uri */
                                    thumbUrl: string;
                                    fullWidth: number | null;
                                    fullHeight: number | null;
                                    thumbWidth: number | null;
                                    thumbHeight: number | null;
                                    originalName: string | null;
                                    displayOrder: number;
                                    createdAt: string;
                                }[];
                                note: string | null;
                                route: string | null;
                                updatedAt: string;
                                visitedOn: string;
                                park: {
                                    name: string;
                                    slug: string;
                                };
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | null;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Visit detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            author: string | null;
                            createdAt: string;
                            id: number;
                            images: {
                                id: number;
                                /** Format: uri */
                                fullUrl: string;
                                /** Format: uri */
                                thumbUrl: string;
                                fullWidth: number | null;
                                fullHeight: number | null;
                                thumbWidth: number | null;
                                thumbHeight: number | null;
                                originalName: string | null;
                                displayOrder: number;
                                createdAt: string;
                            }[];
                            note: string | null;
                            route: string | null;
                            updatedAt: string;
                            visitedOn: string;
                            park: {
                                name: string;
                                slug: string;
                            };
                        };
                    };
                };
                /** @description Visit was not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | null;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted park visit */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Visit was not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | null;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        author?: string | null;
                        note?: string | null;
                        route?: string | null;
                        visitedOn?: string;
                    };
                };
            };
            responses: {
                /** @description Updated park visit */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            author: string | null;
                            createdAt: string;
                            id: number;
                            images: {
                                id: number;
                                /** Format: uri */
                                fullUrl: string;
                                /** Format: uri */
                                thumbUrl: string;
                                fullWidth: number | null;
                                fullHeight: number | null;
                                thumbWidth: number | null;
                                thumbHeight: number | null;
                                originalName: string | null;
                                displayOrder: number;
                                createdAt: string;
                            }[];
                            note: string | null;
                            route: string | null;
                            updatedAt: string;
                            visitedOn: string;
                        };
                    };
                };
                /** @description Visit was not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/parks/{slug}/removed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        removed: boolean;
                    };
                };
            };
            responses: {
                /** @description Updated park removed state */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Park was not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/visits/{id}/images/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | null;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        contentType: "image/jpeg" | "image/png" | "image/webp";
                        fileSizeBytes: number;
                        originalName: string;
                    };
                };
            };
            responses: {
                /** @description Created a direct upload plan for one visit image */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date-time */
                            expiresAt: string;
                            headers: {
                                "content-type": string;
                            };
                            key: string;
                            /** @enum {string} */
                            method: "PUT";
                            /** Format: uri */
                            uploadUrl: string;
                        };
                    };
                };
                /** @description Visit was not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
                /** @description Declared file size exceeds the allowed upload limit */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
                /** @description Invalid upload request */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visits/{id}/images/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | null;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        fullHeight?: number | null;
                        fullWidth?: number | null;
                        key: string;
                        originalName?: string | null;
                    };
                };
            };
            responses: {
                /** @description Stored one directly uploaded visit image */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            image: {
                                id: number;
                                /** Format: uri */
                                fullUrl: string;
                                /** Format: uri */
                                thumbUrl: string;
                                fullWidth: number | null;
                                fullHeight: number | null;
                                thumbWidth: number | null;
                                thumbHeight: number | null;
                                originalName: string | null;
                                displayOrder: number;
                                createdAt: string;
                            };
                        };
                    };
                };
                /** @description Visit was not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
                /** @description Upload is missing or invalid */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visits/{id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | null;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        images?: string;
                    };
                };
            };
            responses: {
                /** @description Uploaded visit images */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            errors: {
                                originalName: string;
                                reason: string;
                            }[];
                            images: {
                                id: number;
                                /** Format: uri */
                                fullUrl: string;
                                /** Format: uri */
                                thumbUrl: string;
                                fullWidth: number | null;
                                fullHeight: number | null;
                                thumbWidth: number | null;
                                thumbHeight: number | null;
                                originalName: string | null;
                                displayOrder: number;
                                createdAt: string;
                            }[];
                        };
                    };
                };
                /** @description No images provided */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
                /** @description Visit was not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
                /** @description File too large */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
                /** @description Invalid file type or all uploads failed */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
                /** @description Server-side multipart uploads are disabled for this runtime */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visits/{visitId}/images/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    imageId: number | null;
                    visitId: number | null;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted visit image */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Image or visit was not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visits/{id}/images/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | null;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        imageIds: number[];
                    };
                };
            };
            responses: {
                /** @description Reordered visit images */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Visit was not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
                /** @description Invalid image order */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Not found */
                            error: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
